### ISSUE TITLE
Reset default icon sizes

### ISSUE THREAD

**Issue by vivadavid** [TheJoeFin/Simple-Icon-File-Maker#13]
Hi,

On the _Icon Sizes_ section, it'd be useful to have an option to reset to the default sizes. Otherwise, you need to select all of them or try to remember which are the default ones.

Thanks!

**Comment by TheJoeFin** [comment]
I have been thinking about this kind of feature.1
1. Should the last "generated" set of icons establish the default settings?
2. Should the last "saved icons" establish the default settings?
3. Should something else?

What do you think?

**Comment by vivadavid** [comment]
When you open an image, there are a few icon sizes selected. I presumed these were carefully chosen and, therefore, the standard ones to be used in Windows. This initial group of sizes would be the one to reset to in my opinion.

Otherwise, we would be talking about allowing the user to create their own set of icon sizes, but this would be too much in my opinion.

**Comment by TheJoeFin** [comment]
@vivadavid I have made some changes to the icon selections let me know if these changes address this issue. 

![image](https://github.com/TheJoeFin/Simple-Icon-File-Maker/assets/7809853/5e9f9806-8ac5-4fff-b444-5120211e102b)

**Comment by vivadavid** [comment]
Hi, @TheJoeFin !

I love the implementation! Thanks!
