### ISSUE TITLE
Adding a changelog

### ISSUE THREAD

**Issue by vivadavid** [TheJoeFin/Simple-Icon-File-Maker#14]
Hi,

I've just updated to version 1.4.0.0, but I can't be sure what the changes are. Would it be possible to add a _Changelog_ section on the app?

Thanks!

**Comment by TheJoeFin** [comment]
The major change is the UX redesign.

**Comment by TheJoeFin** [comment]
There is a change log in the app now under the app info
![image](https://github.com/user-attachments/assets/32fbd11e-87a7-4627-ab0b-24f1e495ed8b)

**Comment by vivadavid** [comment]
Thanks! Appreciated! :-)
