### ISSUE TITLE
Add option for open .ico or drag

### ISSUE THREAD

**Issue by maisondasilva** [TheJoeFin/Simple-Icon-File-Maker#15]
I was able to open an .ico file to edit but it doesn't appear as an accepted format, would you be able to add that? Even selecting all .ico files does not appear!

![image](https://user-images.githubusercontent.com/11423362/235697763-32266bf6-c6bd-4252-bc61-adb00c6cde50.png)

**Comment by TheJoeFin** [comment]
I am planning on adding .ico files as a supported format. The delay comes from the multiple sizes contained within the .ico file and making sure they are parsed properly.

**Comment by maisondasilva** [comment]
Thanks for the great project and design! @TheJoeFin
