### ISSUE TITLE
Use a sharper BitmapScalingMode for previews

### ISSUE THREAD

**Issue by TheJoeFin** [TheJoeFin/Simple-Icon-File-Maker#16]
https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.bitmapscalingmode?view=windowsdesktop-8.0

Probably NearestNeighbor, but need to experiment.

**Comment by michael-hawker** [comment]
@TheJoeFin is this what you need? 🦙 https://stackoverflow.com/questions/41210819/nearest-neighbor-rendering-in-uwp

**Comment by TheJoeFin** [comment]
I am using ImageMagick to scale the source down to the different sizes. The images from that process are good. 
The problem I am having is when displaying those small, say 16x16, images on the Image control within the Viewbox control they look blurred when scaling them up.

Is there a better way I should be "zooming in" on the small sizes? Maybe this is an issue with the Viewbox.

**Comment by michael-hawker** [comment]
I think the suggestion here is to use the BitmapTransform in the UI layer to scale the image back up to the target DPI/size to display in the Image over using Viewbox?

But that does seem a bit excessive.

What happens if you don't put the image in the Viewbox and just resize the Image control with the Uniform stretch - is it the same behavior then?

**Comment by TheJoeFin** [comment]
I removed the Viewbox and have the same problem.

Here on the left is the preview in Simple Icon File Maker and on the right is the preview of the same file in the photos app. 🤔

<img width="804" alt="image" src="https://github.com/TheJoeFin/Simple-Icon-File-Maker/assets/7809853/3ae95d79-96a0-489f-bcf3-df4781d76919">

**Comment by TheJoeFin** [comment]
I was able to finally solve this issue. I did so with the help of StackOverflow and Composition APIs.

This method removed the sub-pixel rendering or anti-aliasing effect I was seeing when using a standard Image or Viewbox uniform to fill scale option.

<img width="677" alt="image" src="https://github.com/TheJoeFin/Simple-Icon-File-Maker/assets/7809853/9d901ddc-ceb6-4bcb-930f-8743bbd1f03d">


To see how:
https://github.com/TheJoeFin/Simple-Icon-File-Maker/blob/2f9d6751f36ecf3524d0f3f823a46b6ce84ba3df/Simple%20Icon%20File%20Maker/Simple%20Icon%20File%20Maker/Controls/PreviewImage.xaml.cs#L114-L158
