### ISSUE TITLE
Bulk Convert Multiple Images

### ISSUE THREAD

**Issue by Scarlywebs** [TheJoeFin/Simple-Icon-File-Maker#23]
Hi, I really like your app and has been very useful. I was wondering would it be possible to add a bulk convert for multiple images? So instead of just doing one at time we could have an option for bulk converting a few icons at a time.

**Comment by TheJoeFin** [comment]
This is a great idea!

**Comment by TheJoeFin** [comment]
@Scarlywebs As I've been thinking about this there are a few questions which come to mind. 

1. Do you expect to see previews of the icon sizes when doing a bulk .ICO file creation?
2. Do you have any examples of programs which do a similar kind of batch work which you think does a good job?

**Comment by Scarlywebs** [comment]
Hey @TheJoeFin thanks for reply, below i anwsered your questions.
**_Do you expect to see previews of the icon sizes when doing a bulk .ICO file creation?_**
This is fine for a single icon but would be messy to see preview or every size per icon from bulk batch, just a simple preview of what icon was converted usually is fine. But if you want you can also create a previoew of the icon that was converted and then maybe have a dropdown of the sizes of the icons. Hope that makes sense. 

**_Do you have any examples of programs which do a similar kind of batch work which you think does a good job?_**
Honestly yours is the best one. Everything out there right now is either too old, doesn't convert batch ICO files or have to pay heavily for batch conversiont.  The site i am currently using is the only best example i got, below is the image that can batch convert icons for free. And there interface not that bad but can be better.

![image](https://github.com/TheJoeFin/Simple-Icon-File-Maker/assets/104298793/e2bb7e37-c215-4b9f-96c6-5afc830dc9e2)

If you want you can give me your buisness email and I can do free UI design template to give a better idea how maybe things could work. :)
