### ISSUE TITLE
Arm64 removed?

### ISSUE THREAD

**Issue by hawkerm** [TheJoeFin/Simple-Icon-File-Maker#24]
Was confused by the comment on the commit here as it seemed unintentional? bafc557fe00b9dbef109e8b037026f5290bb68c7

But it's still missing in the source:

https://github.com/TheJoeFin/Simple-Icon-File-Maker/blob/2d6ccf45a754b7c9444cbe34fbcd5f54f6819e94/Simple%20Icon%20File%20Maker/Simple%20Icon%20File%20Maker%20(Package)/Simple%20Icon%20File%20Maker%20(Package).wapproj#L48

Assuming the dependent libraries support it, then it should make the app work better on Arm based devices?

**Comment by TheJoeFin** [comment]
It was removed when I was packaging and I don't have any ARM devices to test on. I asked @Snickler if he would test for me and he said he would. So once I get the thumbs up from him ARM will get added back. Unless you have an ARM device you could test on?

**Comment by snickler** [comment]
> It was removed when I was packaging and I don't have any ARM devices to test on. I asked @Snickler if he would test for me and he said he would. So once I get the thumbs up from him ARM will get added back. Unless you have an ARM device you could test on?

Give me 20 and I'll have an answer for ya

**Comment by snickler** [comment]
@TheJoeFin - We are good to go. 

- Tested with creating a new QR code to Google's website
- Saved in both PNG and SVG
- Opened the resulting saved QR code image files
![image](https://github.com/TheJoeFin/Simple-Icon-File-Maker/assets/4016293/b4f458ce-1a9c-468a-9b8e-6c9a7a3cd5bd)

**Comment by TheJoeFin** [comment]
Awesome!! ARM is back!!
