### ISSUE TITLE
[FEAT] 

### ISSUE THREAD

**Issue by poa00** [TheJoeFin/Simple-Icon-File-Maker#37]
Maybe not a full-fledged image editor, but it would be awesome if (probably a PRO feature) the app had an "apply theme" function.  Where you can generate slightly lighter/darker versions of an icon.  This would be useful, for instance, where a person is generating tray icons for an application and needs different variations to represent different states of the application. For example, when an app is in a disabled state, the system tray would display a darker/dimmer version of the icon, as opposed to the default version displayed when the application is active.

**Comment by TheJoeFin** [comment]
This is a cool idea!

**Comment by TheJoeFin** [comment]
A version of this feature is out in 1.10 which was just submitted to the Store. I am going to break this up into a few more focused issues which will be easier to deliver and track
