### ISSUE TITLE
Simple Icon File Maker Pro - license & permission issue

### ISSUE THREAD

**Issue by cbortea** [TheJoeFin/Simple-Icon-File-Maker#39]
Hi,

I just bought the pro version of this app (installed from Microsoft Store), the "Get Pro" button dissapeared and I still cannot get the other sizes of the .ico file.

![image](https://github.com/user-attachments/assets/60c7f711-4782-49cc-a034-52c4f48d622d)

Best regards,
Claudiu

**Comment by TheJoeFin** [comment]
Hello Claudiu,
That doesn't sound right, sorry this is happening. Have you closed and opened the app again? Let me know if that works.

**Comment by cbortea** [comment]
Hi Joe,

Thank you for your response!

Sadly it didn't work even after reopening the app. I can say that I tried almost every possible troubleshooting step, including reinstall and it still did not work.

Tried to look through the code, but didn't really have the time to pay enough attention to look through the entire activation and purchase verification flow.

**Comment by TheJoeFin** [comment]
@cbortea if you are still having this issue can you email me directly so I can get more specific details about your system and configuration? joe at joefinapps dot com.

**Comment by TheJoeFin** [comment]
Actually I just looked at your screenshot and realized what is going on. Simple Icon File Maker does not scale an image up. If the image is 48x48 it will not scale up to larger sizes. If you want to get all of those sizes in your icon you will need to provide a source image which is larger.
