### ISSUE TITLE
Unable to Purchase Pro

### ISSUE THREAD

**Issue by pa-0** [TheJoeFin/Simple-Icon-File-Maker#42]
![image](https://github.com/user-attachments/assets/2b0e6adc-d295-4856-8dd8-12fd5c27d5c4)
This is what appears when I click <kbd>Upgrade to Pro</kbd>.

**Comment by TheJoeFin** [comment]
That might be an issue with the Store, have you been experiencing this issue for some time or just once?

**Comment by pa-0** [comment]
Yesterday was the first time I tried purchasing the app. After receiving the error, I uninstalled, restarted, downloaded/installed it again today.  I tried upgrading once more, but still no dice.

**Comment by TheJoeFin** [comment]
It is strange that this is happening, I suspect there is an issue with the Microsoft Store on your device. For now the workaround is to disable internet on your device then launch Simple Icon File Maker, clicking on the "buy Pro" should enable the features. Then it is set as long as the app is installed and internet can be enabled again. This does not grant pro to your account, so if you reinstall the app you'll lose the features again. Let me know if this works for you.

**Comment by pa-0** [comment]
Is there a website I can navigate to where I can purchase Pro and associate it with my Microsoft account?

**Comment by TheJoeFin** [comment]
There isn't a website or anything, try this link and see if it enables Pro for your account:
http://go.microsoft.com/fwlink/?LinkId=532540&mstoken=G2GQG-CF7D7-KH6C3-RFFTG-2499Z

**Comment by pa-0** [comment]
I'll let you know in a second.

**Comment by pa-0** [comment]
That worked.  Do you have a venmo / paypal you can share with me?

**Comment by TheJoeFin** [comment]
Good to hear it works!

https://www.paypal.com/paypalme/JosephFinney

**Comment by TheJoeFin** [comment]
@pa-0 thank you! Let me know if there is anything else that can improve the app!
